service: mealpal-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 120 # 2 minutes
  iamRoleStatements:
      - Effect: Allow
        Action:
          - kms:Decrypt
        Resource: 'arn:aws:kms:*:*:key/*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: mealpal.main.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'