service: mealpal-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: mealpal.main.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    awsKmsKeyArn: 'arn:aws:kms:us-east-1:481497395090:key/6ea89d44-c4e3-477e-92d8-37ddf789fa09'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'