service: mealpal-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 120 # 2 minutes
  iamRoleStatements:
      - Effect: Allow
        Action:
          - kms:Decrypt
        Resource: 'arn:aws:kms:*:*:key/*'
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-east-1:481497395090:table/distance_matrix"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: mealpal.wsgi.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'